version: '3.8'

services:
  drowsiness_detection:
    build:
      context: ./drowsiness_detection
      dockerfile: Dockerfile
    container_name: drowsiness_detection
    ports:
      - "5002:5002"
    restart: always
    environment:
      - TZ=Asia/Jakarta

  face_recognition:
    build:
      context: ./face_recognition
      dockerfile: Dockerfile
    container_name: face_recognition
    ports:
      - "5001:5001"
    restart: always
    environment:
      - TZ=Asia/Jakarta
