version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ./traefik/traefik_dynamic.yaml:/etc/traefik/dynamic.yaml:ro
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=admin@securin.cloud  
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    networks:
      - securin_net

  web_dashboard:
    build:
      context: ./web_dashboard
      dockerfile: Dockerfile
    container_name: web_dashboard
    restart: unless-stopped
    networks:
      - securin_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dashboard.securin.cloud`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls.certresolver=le
      - traefik.http.routers.dashboard.middlewares=redirect-to-https@file

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin12345
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ORG=securin
      - DOCKER_INFLUXDB_INIT_BUCKET=securinbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=rahasia_securin
      - INFLUXDB_HTTP_CORS_ENABLED=true
    volumes:
      - ./influxdb:/var/lib/influxdb2
    networks:
      - securin_net

networks:
  securin_net:
    driver: bridge

volumes:
  traefik_letsencrypt:
